name       : spice-gtk
version    : '0.38'
release    : 18
source     :
    - https://www.spice-space.org/download/gtk/spice-gtk-0.38.tar.xz : 5ae974731baf2b41316d4f0b3ae0c2e47f00bff91a5a617e189cd3dedcd96d8e
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
description: |
    Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gusb)
    - pkgconfig(libcacard)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusbredirhost)
    - pkgconfig(opus)
    - pkgconfig(pixman-1)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(spice-protocol)
    - acl-devel
    - lz4-devel
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - valadoc
setup      : |
    %meson_configure -Dusb-ids-path="/usr/share/hwdata/usb.ids"
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
