name       : spice-gtk
version    : '0.39'
release    : 22
source     :
    - https://www.spice-space.org/download/gtk/spice-gtk-0.39.tar.xz : 23acbee197eaaec9bce6e6bfd885bd8f79708332639243ff04833020865713cd
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
description: |
    Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gusb)
    - pkgconfig(libacl)
    - pkgconfig(liblz4)
    - pkgconfig(libcacard)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusbredirhost)
    - pkgconfig(opus)
    - pkgconfig(pixman-1)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(spice-protocol)
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - valadoc
setup      : |
    %meson_configure -Dusb-ids-path="/usr/share/hwdata/usb.ids"
build      : |
    %ninja_build
install    : |
    %ninja_install
    chmod 4755 $installdir/usr/lib64/spice-gtk/spice-client-glib-usb-acl-helper
check      : |
    %ninja_check
