name       : spice-gtk
version    : '0.36'
release    : 16
source     :
    - https://www.spice-space.org/download/gtk/spice-gtk-0.36.tar.bz2 : 7126c3584df12d40dcf4970f5f46fafd65b757620f911687e549f7da5c8fd7cd
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
description: |
    Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gusb)
    - pkgconfig(libcacard)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusbredirhost)
    - pkgconfig(opus)
    - pkgconfig(pixman-1)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(spice-protocol)
    - acl-devel
    - lz4-devel
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - valadoc
setup      : |
    %configure --disable-static \
               --enable-usbredir \
               --enable-pie \
               --enable-vala \
               --with-usb-ids-path=/usr/share/hwdata/usb.ids
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
