name       : spice-gtk
version    : 0.29
release    : 1
source     :
    - http://www.spice-space.org/download/gtk/spice-gtk-0.29.tar.bz2 : 44c7e22713246a2054c3c3b6e0280fd4c1fdbd2c8d33e5eb95bcda4748d5e973
license    : LGPL-2.1
summary    : Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
description: |
    Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
builddeps  :
    - pkgconfig(pixman-1)
    - pkgconfig(openssl)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(glib-2.0)
    - pkgconfig(cairo)
    - libjpeg-turbo-devel
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libusb-1.0)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(pygtk-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
