name       : spice-gtk
version    : '0.34'
release    : 11
source     :
    - https://www.spice-space.org/download/gtk/spice-gtk-0.34.tar.bz2 : e9720e01165f8451c9f3f58ad50e3afb990993b81cc2db86b3661b7ac5b976ee
license    : LGPL-2.1
component  : desktop.library
summary    : Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
description: |
    Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gusb)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusbredirhost)
    - pkgconfig(pixman-1)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(spice-protocol)
    - acl-devel
    - lz4-devel
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
setup      : |
    %configure --disable-static \
               --enable-usbredir \
               --enable-pie \
               --with-usb-ids-path=/usr/share/hwdata/usb.ids
build      : |
    %make
install    : |
    %make_install
