name       : spice-gtk
version    : 0.33
release    : 4
source     :
    - https://www.spice-space.org/download/gtk/spice-gtk-0.33.tar.bz2 : 7daf33b786ab8ebc9fe6e7b11745100ee1ab66e61a5811d1d5aabe4d66eaaf39
license    : LGPL-2.1
component  : desktop.library
summary    : Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
description: |
    Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
builddeps  :
    - pkgconfig(pixman-1)
    - pkgconfig(openssl)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(glib-2.0)
    - pkgconfig(cairo)
    - libjpeg-turbo-devel
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libusb-1.0)
    - pkgconfig(gusb)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(libusbredirhost)
    - lz4-devel
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
setup      : |
    %configure --disable-static \
               --enable-usbredir \
               --enable-pie
build      : |
    %make
install    : |
    %make_install
