name       : spice-gtk
version    : 0.30
release    : 2
source     :
    - http://www.spice-space.org/download/gtk/spice-gtk-0.30.tar.bz2 : e23323fa399efba17b3c18475ef10a29815851be5e7dbedd246b28ee8eb1379c
license    : LGPL-2.1
summary    : Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
description: |
    Gtk client and libraries for SPICE remote desktop servers (gtk3 version)
builddeps  :
    - pkgconfig(pixman-1)
    - pkgconfig(openssl)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(glib-2.0)
    - pkgconfig(cairo)
    - libjpeg-turbo-devel
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libusb-1.0)
    - pkgconfig(gusb)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(libusbredirhost)
    - lz4-devel
setup      : |
    %configure --disable-static \
               --enable-usbredir \
               --enable-pie
build      : |
    %make
install    : |
    %make_install
